export const ADD_ARTICLE = 'ADD_ARTICLE';
export const INFO_ARTICLE = 'INFO_ARTICLE';
export const EDIT_ARTICLE = 'EDIT_ARTICLE';
export const REMOVE_ARTICLE = 'REMOVE_ARTICLE';
export const ALL_ARTICLES = 'ALL_ARTICLES';